name: Symfony Docker CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build & Test Docker Container
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: |
          docker build -t design-oop:latest .

      - name: Run PHP Tests
        run: |
          docker run --rm design-oop:latest vendor/bin/phpunit --testdox

  # deploy:
  #   name: Deploy to Production Server
  #   runs-on: ubuntu-latest
  #   needs: build
  #   if: github.ref == 'refs/heads/main'

  #   steps:
  #     - name: Deploy via SSH
  #       uses: appleboy/ssh-action@v0.1.10
  #       with:
  #         host: ${{ secrets.SSH_HOST }}
  #         username: ${{ secrets.SSH_USER }}
  #         password: ${{ secrets.SSH_PASS }}
  #         script: |
  #           docker pull ${{ secrets.DOCKER_USERNAME }}/design-oop:latest
  #           docker stop symfony_app || true
  #           docker rm symfony_app || true
  #           docker run -d --name symfony_app -p 80:80 ${{ secrets.DOCKER_USERNAME }}/design-oop:latest
