name: Symfony Docker CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build & Test Docker Container
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: |
          docker build -t design-oop:latest .

      - name: Install Composer dependencies
        run: |
          docker run --rm design-oop:latest composer install

      - name: Run PHP Tests
        run: |
          docker run --rm design-oop:latest vendor/bin/phpunit --testdox
